void roomText(List<List<String>> roomTextList){
  List<List<String>> createText = [
    ['You are in a chamber that you can only describe as an occult like',
  'sacrificial chamber. The room is light up only by torches and in the centre',
  'is a stone “bed” both covered and surrounded by occult symbolisms and',
  'pentagrams. The walls are made of smooth stone and wooden beams and to',
  'the east is a doorway leading out.'],
    ['You are in a simple hallway made of smooth stone and wooden beams just',
    'like the sacrificial chamber, the only things of note are a path to the north',
    'leading to a small room, a door to the east with a padlock that resembles a',
    'goat’s head with five eyes that requires a letter combination and the path west',
    'leading to the sacrificial chamber.'],
    ['The room has a pedestal in the middle with a black piece of paper',
  'on top of it. The pedestal is surrounded by many occult symbols and runes,',
  'more so than the sacrificial room you woke up in. The paper has golden',
  'etchings upon it and for some strange reason you feel safe close to it. The only',
  'other thing of note is the doorway out to the west.'],
    ['The small room seems to be halfway built as the smooth',
  'stone of the tunnel changes into crude cobblestone walls. The wall to the north',
  'looks especially crude and feels like you could disassemble it rebuild easily',
  'even with your lack of building skills. Other than the crude wall north there is a',
  'passage leading south.'],
    ['You are in a simple hallway made of smooth stones and help up by wooden',
  'beams, some simple tapestry line the walls and a small table with two chairs are',
  'set in the corner. To the tunnel keep going east and to the south is the crude',
  'cobblestone wall leading to the chamber you woke up in.'],
    ['You are in a simple hallway made of smooth stone and wooden beams. It is',
  'parsley decorated with a few tables and chairs but with nothing of not on them.',
  'To the north is a door with a bronze padlock, to the east the tunnel continues',
  'and to the west as well.'],
    ['You are in a simple hallway made of smooth stone and wooden beams',
  'sparsely decorated by tapestry and a picture of some people in robes praying to',
  'a ritual-circle. To the north is a doorway with a placard above it written with the',
  'word “armoury”, to the south is an undisclosed room with a bronze padlock and',
  'to the west the hallway continues.'],
    ['The armoury is filled to the brim with rusted weapons which look as if',
  'they will break at any moment and empty weapon-racks where staves and such',
  'would be placed. In the corner there is a messy table filled with scrolls and tools',
  'but as well as a keyring with bronze keys. To the south is a doorway leading to',
  'a hallway.'],
    ['The small room is made of wood, most likely some sort of oak, and filled',
  'with simple cleaning utensils such as brooms and cloths. Other than that, there',
  'is nothing of interest in this room. To the north is a door leading to a hallway.'],
    ['You are in a simple hallway made of smooth stone and wooden beams',
  'decorated with torches to the side and some pictures depicting people in robes.',
  'The hallway seems to get larger and wider to the north whilst remaining the',
  'same size to the south.'],
    ['You are in a wide-open space, something akin to a large gazebo in',
  'the middle of a vast cavern with both stalactites and stalagmites adorning it.',
  'The are is light up by some sort of humming magical sphere that is hovering',
  'around thirty meters up. To the east is a door with a combination lock',
  'resembling a crow with white feathers and two beaks, to the south is a corridor',
  'and to the west is an archway leading to a mid-sized room.'],
    ['You are in a room filled with multiple statues depicting devils and',
  'robed people though the faces are nigh unrecognizable with the dim lighting of',
  'the torches. To the north you see a suspicious statue with scratch-marks on the',
  'floor underneath and besides it. To the east is the open space, to the south is a',
  'well-furnished area and to the west is an ominous room.'],
    ['You are in a dark room illuminated by what seems to be some',
  'sort of floating ethereal blue fire. The room seems to have been carved out of',
  'the ground and in the middle of it is a pedestal with an orb that seems to be',
  'filled with some mysterious power. To the east is the statue room.'],
    ['You are in what seems to be an art gallery filled with different',
  'paintings of demons, wars, and rituals but two of them catch your eye. The',
  'picture to the south depicts a white feathered five-winged demon that has a',
  'lanky body that contorts in unnatural ways and has a head similar to a crow',
  'except it has two maws and under it is written a name “Azhox”. A painting to the',
  'west depicting a person seems to be crooked unlike all the other. Other than',
  'that, the only interesting thing is the way back to the statue room up north.'],
    ['You are in the room hidden by the painting and what you see is a',
  'medium sized room with multiple corpses that look like guards. By their',
  'appearance they have been there for a while. The other thing that catches your',
  'eye is a big iron wall to the south with a minimalist but sturdy door with a',
  'padlock made of similar material. What are or were they guarding in there that',
  'required this much protection?'],
    ['In the room beyond the heavy iron door is a dimly lit room with',
  'blood everywhere. There is blood on the floors, the walls and even the ceiling',
  'which can be no lower than fifty meters high. The walls are adorned with',
  'shackles and on the inside of those very shackles are thorns long enough to',
  'pierce the captives’ bones but what is most frightening about them is their size,',
  'they are seven times bigger than any you have seen. In the middle is a pile of',
  'hat looks like ripped of flesh and on top of it is an ornate key.'],
    ['You are in a room that seems like some sort of study filled with occult',
  'books. To the north are tables filled to the brim with books both opened and',
  'closed and to the east are tables with writing utensils. To the west is the statue',
  'room and to the west seems to be a library.'],
    ['You are in a library filled with old and dusty books, most of which',
  'leather-bound and amongst those some seem to be made of human skin. All the',
  'way to the end of the library is a small desk with a few books on it but as well a',
  'key that seems to be made out of iron. To the east is the study.'],
    ['You are in what appears to be a grand hall, the roof high off the',
  'ground, the floor decorated with carpets, the walls decorated with tapestry of all',
  'shapes and sizes and the hall is light up by chandeliers. To the north is what',
  'seems to be a tapestry room, to the east seems to be a door with an ornate',
  'padlock though you feel something sinister beyond the door and to the west is',
  'the open space.'],
    ['You re in a room where all of the walls are lined with a tapestry',
  'of some kind or another. Most of the tapestries depict demons or rituals but one',
  'of them catches your eyes. The tapestry depicts a goat with seven legs, three',
  'tails and five eyes leading an army of undead to a village. Under the tapestry is',
  'written the name “Ygroth”. To the south is the grand hall.'],
    ['You are in a massive hall not that much unlike the grand hall except',
  'for one thing, the massive amount of bones littered around the floor, some',
  'intact, some crushed and some are even cleaved into smaller pieces, just how',
  'powerful is the darkness? To the east is a tunnel and to the west is the grand',
  'hall.'],
    ['You are in a simple hallway made of smooth stone and wooden beams. The',
  'walls seem to be slightly scorched, and a few tables are upturned. To the north',
  'are rotting crates, the tunnel hallway continues south and to the west is the',
  'skull-littered grand hall.'],
    ['You are in an ill placed together cobblestone room, it is filled',
  'with rotting furniture made of wood and covered with dust. The tapestry that line',
  'the walls have had their colour fade over time and you cant make out what they',
  'are supposed to represent. To the south is the way back to the hallway and to',
  'the west the room opens up into a cave.'],
    ['You are in a cave which is being illuminated by a few small holes',
  'in the ceilings. In the middle of the cave is a natural pond albeit a shallow one.',
  'Near the edge of the pond is a skeleton holding a rusty key. To the east is the',
  'run-down area.'],
    ['You are in a simple hallway made of smooth stone and wooden beams.',
  'There are signs of struggle as parts of the walls are scorched black, some of',
  'the stone floor broken from heavy impacts but the strange thing is that there are',
  'no bodies here, not even blood. The hallway continues north and east.'],
    ['You are in a simple hallway made of smooth stone and wooden beams. The',
  'walls show light scorch marks and a few chairs have been knocked down and',
  'away from the upright tables. To the north is a door with a bronze padlock, to',
  'the south is a door with a rusty padlock and to the west the tunnel continues.'],
    ['You are in a room dimly lit by the torches upon the wall. To the left',
  'and right side of the room are stone tables, all with corpses on top of them. The',
  'corpses at a moment’s glance look normal but upon closer inspection there is',
  'something wrong with each of them. Some are inhumanly longer than others,',
  'some have multiple arms, some have beast-like features implanted instead of',
  'human ones and some are too disfigured to even describe. To the south is a',
  'hallway.'],
    ['You are in a simple hallway made of smooth stone and wooden beams. It is',
  'decorated with a few tables, each having around three to four chairs each. The',
  'walls are decorated with tapestries and a few paintings, yet the room strikes you',
  'as oddly clean. The hallway continues north and to the west is a large room.'],
    ['You are in a quite large room that is filled with barricades and',
  'fence walls. The room has clear signs of a large-scale battle. The floors and',
  'walls show multiple big scorch signs, walls are covered in cut marks and there',
  'are many parts of the floor that are caved or broken from heavy blunt forces.',
  'The strangest thing about this room is that there are no remains. There is a',
  'hallway to the east and south.'],
    ['You are in a simple hallway made of smooth stone and wooden beams.',
  'The hallway has some simple barricades in a somewhat zig-zag pattern,',
  'intended to perhaps funnel enemies. There is a suspicious boulder to the west.',
  'To the north is the room with fortifications and to the west the hallway continues.'],
    ['You are in a somewhat expansive cave that is lit by torches. On the',
  'other end is a small church of some sort whose mural above the door depicts a',
  'skull and three oddly coloured moons. You believe that you remember about',
  'some cult that is obsessed about reanimating and controlling the dead whose',
  'symbol is three moons. To the south is the church entrance and to the west is',
  'the hallway.'],
    ['You are in a church decorated with occult symbolisms and',
  'tapestry and stained-glass art depicting demons and robed figures. At the back',
  'of the church are three statues, two of which are familiar. The one on the left is',
  'Ygroth and the one on the right is Azhox. The statue in the middle resembles a',
  'human with squid like features the most prominent being the head. On the base',
  'of the statue is written “Hozq”. To the south is the way out of the church.'],
    ['You are in a simple hallway made of smooth stone and wooden beams.',
  'The best way that you can describe it is empty. There is nothing here. No',
  'tapestry, paintings, chairs, tables or anything. The hallway is simply empty. To',
  'the north is a door with a squid-like combination-lock, to the west the hallway',
  'continues and to the south is a red room.'],
    ['The room you are in is stained red with blood, all from the floor to',
  'the walls to the ceiling. All round the room re corpses ranging from armoured to',
  'robed to distorted. There are so many bodies that the pile nearly reaches the',
  'roof of the room. There is nothing of interest here except for one body that looks',
  'oddly familiar, the only interesting feature is a small dent on its head. There is a',
  'hallway to the north.'],
  ['The room you are in is fairly small but well lit, not by the torches',
  'but by the sunlight spilling in from the stairway up in front of you. The room has',
  'little to no decorations of note. To the north is the stairway out and to the south',
  'is the hallway you came from.'],
  ];

  roomTextList.addAll(createText);
}
